runtime: python312

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /sitemap\.txt
  static_files: sitemap.txt
  upload: sitemap\.txt

- url: /static
  static_dir: static

- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 302

error_handlers:
- file: templates/error-500.html
